version: "3"
services:
  registry:
    image: registry
    environment:
      - REGISTRY_STORAGE_S3_ACCESSKEY=KEY
      - REGISTRY_STORAGE_S3_SECRETKEY=SECRETKEY
    ports:
      - 5000:5000
    volumes:
      - ./dockers/registry/config.yml:/etc/docker/registry/config.yml

  registry-dashboard:
    image: konradkleine/docker-registry-frontend:v2
    environment:
       - ENV_DOCKER_REGISTRY_HOST=registry
       - ENV_DOCKER_REGISTRY_PORT=5000
    links:
      - registry

  nginx:
    build: dockers/nginx
    ports:
      - 8181:80
    links:
      - registry-dashboard
    volumes:
      - ./dockers/nginx/conf.d:/etc/nginx/conf.d
